"""Create PhoneBook

Revision ID: 99558476c827
Revises: 
Create Date: 2020-08-11 21:02:53.960033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99558476c827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('hero_name', sa.String(length=150), nullable=True),
    sa.Column('phone_num', sa.String(length=15), nullable=False),
    sa.Column('email_add', sa.String(length=150), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_book')
    # ### end Alembic commands ###
