"""Update Table to include password

Revision ID: c6c1bdd11ee8
Revises: 99558476c827
Create Date: 2020-08-12 19:01:51.264969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c1bdd11ee8'
down_revision = '99558476c827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_book', 'hero_name',
               existing_type=sa.VARCHAR(length=150))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_book', 'hero_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('phone_book', 'password')
    # ### end Alembic commands ###
